linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - exhaustruct # Very noisy, hard to disable when want zero values
    - forcetypeassert # If its wrong, we want to know
    - nlreturn # Not desired
    - godox # Yes. The project is in progress
    - depguard # Not desired
    - varnamelen # Not desired
    - cyclop # Flags big simple switch statements

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  gomoddirectives:
    replace-local: true
  ireturn:
    allow:
      - tea.Model
      - error
      - stdlib
      - empty
      - generic
  mnd:
    ignored-files:
      - 'monitor/.*.go' # UI code has many magic layout numbers...
      - 'main.go' # Main file allowed, as it is example code
  paralleltest:
    # eCAL uses global state, any test using Initialize can't be run in parallel
    ignore-missing: true

issues:
  exclude-rules:
    - path: monitor/styles.go
      linters:
        - gochecknoglobals
  exclude-dirs:
    - cmd/monitor/internal/
