version: "2"
linters:
  default: all
  disable:
    - cyclop # Flags big simple switch statements
    - depguard # Not desired
    - exhaustruct # Very noisy, hard to disable when want zero values
    - forcetypeassert # If its wrong, we want to know
    - godox # Yes. The project is in progress
    - nlreturn # Not desired
    - varnamelen # Not desired
    - wsl # Deprecated
  settings:
    gomoddirectives:
      replace-local: true
    ireturn:
      allow:
        - tea.Model
        - error
        - stdlib
        - empty
        - generic
    mnd:
      ignored-numbers:
        - "2"
      ignored-files:
        - monitor/.*.go # UI code has many magic layout numbers...
        - main.go # Main file allowed, as it is example code
    paralleltest:
    # eCAL uses global state, any test using Initialize can't be run in parallel
      ignore-missing: true
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: strict # Must obey convention: https://go.dev/s/generatedcode
    presets: []
    rules:
      - linters:
          - gochecknoglobals
        path: monitor/styles.go
    paths:
      - cmd/monitor/internal/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - cmd/monitor/internal/
      - third_party$
      - builtin$
      - examples$
