linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - execinquery # Deprecated
    - gomnd # Deprecated name of mnd
    - exhaustruct # Very noisy, hard to disable when want zero values
    - forcetypeassert # If its wrong, we want to know
    - nlreturn # Not desired
    - godox # Yes. The project is in progress
    - gochecknoglobals
    - nonamedreturns
    - paralleltest
    - predeclared
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - cyclop
    - revive
    - funlen
    - unparam
    - exhaustive
    - inamedparam

linters-settings:
  ireturn:
    allow:
      - tea.Model
      - error
      - stdlib
      - empty
      - generic
  gci:
    sections:
      - standard
      - default
      - localmodule
  mnd:
    ignored-files:
      - 'monitor/.*.go' # UI code has many magic layout numbers...
      - 'main.go' # Main file allowed, as it is example code
