linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - execinquery # Deprecated
    - gci
    - forbidigo
    - gocritic
    - godox
    - gomnd
    - gochecknoglobals
    - gosec
    - ireturn
    - exhaustruct
    - mnd
    - forcetypeassert
    - nlreturn
    - nonamedreturns
    - paralleltest
    - predeclared
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - stylecheck
    - depguard
    - cyclop
    - revive
    - funlen
    - unparam
    - exhaustive
    - inamedparam
