linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - execinquery # Deprecated
    - exhaustruct # Very noisy, hard to disable when want zero values
    - forcetypeassert # If its wrong, we want to know
    - nlreturn # Not desired
    - godox
    - gomnd
    - gochecknoglobals
    - gosec
    - mnd
    - nonamedreturns
    - paralleltest
    - predeclared
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - cyclop
    - revive
    - funlen
    - unparam
    - exhaustive
    - inamedparam

linters-settings:
  ireturn:
    allow:
      - tea.Model
      - error
      - stdlib
      - empty
      - generic
  gci:
    sections:
      - standard
      - default
      - localmodule
